default_context:
  project_name: 'au-lover'
  project_slug: 'au-lover'
  domain_main: 'au-lover.com'
  domain_staging: 'stag.au-lover.com'
  docker_swarm_stack_name_main: 'au-lover-com'
  docker_swarm_stack_name_staging: 'stag-au-lover-com'
  secret_key: 'a6799afa2c1f14095bb7b4cd30f35c6601da5e7ae7d20b404af101fa92d7121e'
  first_superuser: 'admin'
  first_superuser_password: '060588'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.au-lover.com", "https://stag.au-lover.com", "https://au-lover.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@au-lover.com'
  postgres_password: 'xxxxx'
  pgadmin_default_user: 'xxxxx'
  pgadmin_default_user_password: 'xxxxx'
  traefik_constraint_tag: 'au-lover.com'
  traefik_constraint_tag_staging: 'stag.au-lover.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:060588'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
